common/models/Roles.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\db\Expression;
use common\models\People;

/**
 * This is the model class for table "ROLES".
 *
 * @property string $ID
 * @property string $NAME
 * @property integer $DELETED
 * @property string $DELETED_DATE
 * @property string $CREATED_AT
 * @property string $UPDATED_AT
 * @property integer $CREATED_BY
 * @property integer $UPDATED_BY
 */
class Roles extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    const STATUS_DELETED = 1;
    const STATUS_ACTIVE = 0;

    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'CREATED_AT',
                'updatedAtAttribute' => 'UPDATED_AT',
                'value' => date('d-M-y h.i.s a'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'CREATED_BY',
                'updatedByAttribute' => 'UPDATED_BY',
                'value' => Yii::$app->user->id,
            ],
        ];
    }

    public static function tableName() {
        return 'ROLES';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
//            [['ID'], 'required'],
            [['ID'], 'number'],
            [['DELETED', 'CREATED_BY', 'UPDATED_BY'], 'integer'],
            [['DELETED_DATE', 'CREATED_AT', 'UPDATED_AT'], 'safe'],
            [['NAME'], 'string', 'max' => 255],
            [['ID'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'ID' => Yii::t('app', 'ID'),
            'NAME' => Yii::t('app', 'Akses'),
            'DELETED' => Yii::t('app', 'Status'),
            'DELETED_DATE' => Yii::t('app', 'Tarikh Status'),
            'CREATED_AT' => Yii::t('app', 'Tarikh Dijana'),
            'UPDATED_AT' => Yii::t('app', 'Tarikh Dikemaskini'),
            'CREATED_BY' => Yii::t('app', 'Dijana Oleh'),
            'UPDATED_BY' => Yii::t('app', 'Dikemaskini Oleh'),
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function getCreator() {
        return $this->hasOne(People::className(), ['ID' => 'CREATED_BY']);
    }
    public function getUpdator() {
        return $this->hasOne(People::className(), ['ID' => 'UPDATED_BY']);
    }
}

frontend/controllers/OfficialFormController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\FormGenerator;
use common\models\Inventories;
use common\models\KewpsForm;
use common\models\Orders;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;

class OfficialFormController extends \yii\web\Controller {

	public function actionIndex() {
		return $this->render('index');
	}

	public function actionFormGenerator() {
		$model = new FormGenerator();
		$year = \common\models\TransactionsAll::find()
		->select('EXTRACT(YEAR FROM CHECK_DATE) as YEAR')
		->distinct()->indexBy('YEAR')->asArray()->all();
		$yearList = ArrayHelper::map($year,'YEAR','YEAR');
		$monthList = [
		1 => 'Januari',
		2 => 'Febuari',
		3 => 'Mac',
		4 => 'April',
		5 => 'Mei',
		6 => 'Jun',
		7 => 'Julai',
		8 => 'Ogos',
		9 => 'September',
		10 => 'Oktober',
		11 => 'November',
		12 => 'Disember',
		];
		$formId = [
		// 3 => 'KEW.PS-3 ()',
		4 => 'KEW.PS-4 (KAD PETAK)',
		5 => 'KEW.PS-5 (SENARAI DAFTAR KAD KAWALAN STOK)',
		7 => 'KEW.PS-7 (PENENTUAN KUMPULAN STOK)',
		8 => 'KEW.PS-8 (LABEL FIFO)',
		9 => 'KEW.PS-9 (SENARAI STOK BERTARIKH LUPUT)',
		10 => 'KEW.PS-10 (BORANG PESANAN DAN PENGELUARAN STOK)',
		11 => 'KEW.PS-11 (BORANG PEMESANAN STOK)',
		13 => 'KEW.PS-13 (LAPORAN KEDUDUKAN STOK)',
		14 => 'KEW.PS-14 (LAPORAN PEMERIKSAAN / VERIFIKASI STOR)',
		17 => 'KEW.PS-17 (PENYATA PELARASAN STOK)',
		18 => 'KEW.PS-18 (PERAKUAN AMBIL ALIH)',
		];
		$inventoryList = Inventories::find()->andFilterWhere(['DELETED' => 0])->asArray()->all();
		$inventoriesArray = ArrayHelper::map($inventoryList, 'ID', function($model) {return $model['CODE_NO'] . ' - ' .$model['DESCRIPTION'] ;});
		$orderList = Orders::find()
		->andFilterWhere(['DELETED' => 0])
		// ->andFilterWhere(['APPROVED' => 1])
		// ->orderBy(['ID'=>SORT_ASC])
		// ->orderBy(['to_number(substr([[ORDER_NO]],9))'=>SORT_ASC])
		->orderBy(['ID'=>SORT_DESC])
		->asArray()->all();
		$ordersArray = ArrayHelper::map($orderList, 'ID', 'ORDER_NO');
		$formName = new FormGenerator();
//        var_dump($model);die();
		if ($model->load(Yii::$app->request->post())) {
			// var_dump(Yii::$app->request->post());die();
			if ($model->FORM_ID == 3) {
				// KewpsForm::pdfKewps4(
				//     $id = $model->INVENTORY_ID,
				//     $year = $model->YEAR,
				//     $month = $model->MONTH
				//     );
			} else if ($model->FORM_ID == 4) {
				KewpsForm::pdfKewps4(
					$id = $model->INVENTORY_ID,
					$year = $model->YEAR,
					$month = $model->MONTH,
					// $printAll = $model->printAll
					$printAll = 0
					);
			} else if ($model->FORM_ID == 5) {
				KewpsForm::pdfKewps5(
					$id = $model->INVENTORY_LIST
					);
			} else if ($model->FORM_ID == 7) {
				KewpsForm::pdfKewps7(
					$id = $model->INVENTORY_LIST,
					$year = $model->YEAR
					);
			} else if ($model->FORM_ID == 8) {
				KewpsForm::pdfKewps8(
					$id = $model->INVENTORY_LIST
					);
			} else if ($model->FORM_ID == 9) {
				KewpsForm::pdfKewps9(
					$id = $model->INVENTORY_LIST
					);
			} else if ($model->FORM_ID == 10) {
				KewpsForm::pdfKewps10(
					$id = $model->ORDER_ID
					);

			} else if ($model->FORM_ID == 11) {
				KewpsForm::pdfKewps11(
					$id = $model->ORDER_ID
					);
			} else if ($model->FORM_ID == 13) {
				KewpsForm::pdfKewps13(
					$year = $model->YEAR
					);
			} else if ($model->FORM_ID == 14) {
				KewpsForm::pdfKewps14(
					$id = $model->INVENTORY_LIST,
					$year = $model->YEAR
					);
			} else if ($model->FORM_ID == 17) {
				KewpsForm::pdfKewps17(
					$id = $model->INVENTORY_LIST
					);
			} else if ($model->FORM_ID == 18) {
				KewpsForm::pdfKewps18(
					$id = $model->INVENTORY_LIST
					);
			}
		}

		return $this->render('form-generator', [
			'model' => $model,
			'formId' => $formId,
			'yearList' => $yearList,
			'monthList' => $monthList,
			'ordersArray' => $ordersArray,
			'inventoriesArray' => $inventoriesArray,
			]);
	}
	public function actionFormOptions() {
		$out = [];
		if (isset($_POST['depdrop_parents'])) {
			$parents = $_POST['depdrop_parents'];
			if ($parents != null) {
				$form_id = $parents[0];
				if ($form_id == 3) {
					$out = \common\models\Inventories::find()
					// ->select('ID,CODE_NO,CARD_NO,DESCRIPTION,QUANTITY,LOCATION')
					->select('ID as id,DESCRIPTION as name')
					->asArray()->all();
					// $out  = ArrayHelper::index($out,'ID');

				}
				if ($form_id == 4) {
					$out = \common\models\Orders::find()
					->select('ID as id,ORDER_NO as name')
					// ->select('ORDERS.ID,ORDER_NO,ARAHAN_KERJA_ID,APPROVED,VEHICLE_ID')
					// ->with('arahanKerja','vehicle')
					->asArray()->all();
				}
				echo Json::encode(['output' => $out, 'selected' => '']);
				return;
			}
		}
		echo Json::encode(['output' => '', 'selected' => '']);
	}

	public function actionPdfKewps3($id = null) {
		var_dump('note created yet');die();
	}
	public function actionPdfKewps4($id = null) {
		// var_dump($id);die();
		KewpsForm::pdfKewps4($id);
	}

	public function actionPdfKewps5($id = null) {
		KewpsForm::pdfKewps5($id);
	}

	public function actionPdfKewps7($id = [145, 144]) {
		KewpsForm::pdfKewps7($id);
	}

	public function actionPdfKewps8($id = null) {
		KewpsForm::pdfKewps8($id);
	}

	public function actionPdfKewps82($id = null) {
		KewpsForm::pdfKewps82($id);
	}
	public function actionPdfKewps9($id = null) {
		KewpsForm::pdfKewps9($id);
	}

	public function actionPdfKewps10($id = null) {
		KewpsForm::pdfKewps10($id);
	}
	public function actionPdfKewps11($id = null) {
		KewpsForm::pdfKewps11($id);
	}

	public function actionPdfKewps13($id = null, $year = null) {
		KewpsForm::pdfKewps13($id);
	}

	public function actionPdfKewps14($id = null) {
		KewpsForm::pdfKewps14($id);
	}

	public function actionPdfKewps17($id = null) {
		KewpsForm::pdfKewps17($id);
	}

	public function actionPdfKewps18($id = null) {
		KewpsForm::pdfKewps18($id);
	}

}

frontend/views/official-form/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
    // var_dump(url::to(['/official-form/form-options']));die();
$script = <<<JS
// $(document).on('submit', 'form[data-pjax]', function(event) {

//   $.pjax.submit(event, '#pjax-container')
// });
$('#formgenerator-form_id').on('change', function() {
    var formId = $(this).val();
//  iv_id,year,month
    if (formId == 0) {
        $('#inventory_section').hide(800);
        $('#inventories_section').show(800);
        $('#order_section').hide(800);
        $('#timeframe_section').show(800);
        $('#month_section').show(800);
        $('#kewps4_hint').hide(800);
//  iv_id,year,month
    } else if (formId == 4) {
        $('#inventory_section').show(800);
        $('#inventories_section').hide(800);
        $('#order_section').hide(800);
        $('#timeframe_section').show(800);
        $('#month_section').show(800);
        $('#kewps4_hint').show(800);
//  o_id,year,month
    } else if (formId == 0) {
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').show(800);
        $('#timeframe_section').show(800);
        $('#month_section').show(800);
        $('#kewps4_hint').hide(800);
//  o_id
    } else if ($.inArray(formId , ["10","11"] ) > -1) {
        // alert('success');
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').show(800);
        $('#timeframe_section').hide(800);
        $('#month_section').hide(800);
        $('#kewps4_hint').hide(800);
//  iv_id
    } else if ($.inArray(formId , ["5","8","9","17","18"] ) > -1) {
        $('#inventory_section').hide(800);
        $('#inventories_section').show(800);
        $('#order_section').hide(800);
        $('#timeframe_section').hide(800);
        $('#month_section').hide(800);
        $('#kewps4_hint').hide(800);
//  o_id,year
    } else if (formId == 0) {
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').show(800);
        $('#timeframe_section').show(800);
        $('#month_section').hide(800);
        $('#kewps4_hint').hide(800);
//  iv_id,year
    } else if ($.inArray(formId , ["7","14"] ) > -1) {
        $('#inventory_section').hide(800);
        $('#inventories_section').show(800);
        $('#order_section').hide(800);
        $('#timeframe_section').show(800);
        $('#month_section').hide(800);
        $('#kewps4_hint').hide(800);
//  year
    } else if (formId == 13) {
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').hide(800);
        $('#timeframe_section').show(800);
        $('#month_section').hide(800);
        $('#kewps4_hint').hide(800);
//  hide all
    } else {
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').hide(800);
        $('#timeframe_section').hide(800);
        $('#month_section').hide(800);
        $('#kewps4_hint').hide(800);
    }
});
JS;

/* @var $this yii\web\View */
/* @var $model common\models\OrderItems */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-items-form">

    <?php
    // Pjax::begin();
    $this->registerJs($script);
    ?>
    <?php $form = ActiveForm::begin(['id' => 'configform']);?>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <?php echo $form->field($model, 'FORM_ID')->widget(kartik\select2\Select2::className(),
                    [
                        'data'          => $formId,
                        // 'theme' => 'default',
                        'options'       => ['placeholder' => 'Select an inventory ...'],
                        'pluginOptions' => [
                            'allowClear' => true,
                        ]
                    ]);
                    ?>
                </div>
            </div>
            <div class="row" id="inventory_section" style="display: none">
                <div class="col-md-4">
                    <?=
                    $form->field($model, 'INVENTORY_ID')->widget(kartik\select2\Select2::className(), [
                        'data'          => $inventoriesArray,
    // 'theme' => 'default',
                        'options'       => ['placeholder' => 'Select an inventory ...'],
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                    ]);
                    ?>
                </div>
            </div>
            <div class="row" id="inventories_section" style="display: none">
                <div class="col-md-4">
                    <?=
                    $form->field($model, 'INVENTORY_LIST')->widget(kartik\select2\Select2::className(),
                        [
                            'data'          => $inventoriesArray,
        // 'theme' => 'default',
                            'options'       => ['placeholder' => 'Select an inventory ...', 'multiple' => true],
                            'pluginOptions' => [
                                'allowClear' => true,
                            ],
                        ]);
                        ?>
                    </div>
                </div>
                <div class="row" id="order_section" style="display: none">
                    <div class="col-md-4">
                        <?=
                        $form->field($model, 'ORDER_ID')->widget(kartik\select2\Select2::className(),
                            [
                                'data'          => $ordersArray,
        // 'theme' => 'default',
                                'options'       => ['placeholder' => 'Select an order no ...'],
                                'pluginOptions' => [
                                    'allowClear' => true,
                                ],
                            ]);
                            ?>
                        </div>
                    </div>
                    <div class="row" id="timeframe_section" style="display: none">
                        <div class="col-md-4" id="year_section">
                            <?=
                            $form->field($model, 'YEAR')->widget(kartik\select2\Select2::className(),
                                [
                                    'data'          => $yearList,
        // 'theme' => 'default',
                                    'options'       => ['placeholder' => 'Select an year ...'],
                                    'pluginOptions' => [
                                        'allowClear' => true,
                                    ],
                                ]);
                                ?>
                            </div>
                            <div class="col-md-4" id="month_section" style="display: none">
                                <?=
                                $form->field($model, 'MONTH')->widget(kartik\select2\Select2::className(),
                                    [
                                        'data'          => $monthList,
        // 'theme' => 'default',
                                        'options'       => ['placeholder' => 'Select an month ...'],
                                        'pluginOptions' => [
                                            'allowClear' => true,
                                        ],
                                    ]);
                                    ?>
                                </div>
                            </div>
                            <dl id="kewps4_hint" style="display: none">
                                <dt>Nota</dt>
                                <dd>Kosongkan Tahun dan Bulan untuk cetak semua</dd>
                                <dd>Kosongkan Bulan untuk cetak data tahunan</dd>
                                <dd>Isi Tahun dan Bulan untuk cetak data bulanan</dd>
                            </dl>
                            <div>
                                <?=Html::a(Yii::t('app', 'Isi Semula'), ['/official-form/form-generator'], ['id'=>'reset','class' => 'btn btn-default']);
                                ?>
                                <?=Html::submitButton(Yii::t('app', 'Cetak'), ['class' => 'btn btn-primary', 'formtarget' => '_blank']);
                                ?>
                            </div>
                        </div>
                        <?php ActiveForm::end();?>
                        <?php
                            // Pjax::end();
                        ?>
                    </div>

frontend/views/official-form/_kewps102_3.php
<tfoot>
    <tr>
        <td class="foot-head-col-1 foot-head-row-1" style="white-space:nowrap;" colspan="2">Pegawai Pemesan :</td>
        <td class="foot-head-col-2 foot-head-row-1 border-right-bold" style="white-space:nowrap;" colspan="2">Pegawai Penerima :</td>
        <td class="foot-head-col-3 foot-head-row-1" style="white-space:nowrap;" colspan="5">Tarikh Diluluskan dan Direkodkan Oleh :</td>
        <td class="foot-head-col-4 foot-head-row-1" style="white-space:nowrap;" colspan="2">Dikeluarkan dan Direkodkan Oleh :</td>
    </tr>
    <tr>
        <td class="no-border"><strong>aNama :</strong></td>
        <td class="no-border pull-right border-right" style="font-size:12;"><?= mb_strimwidth(strtoupper($items[0]['order']['ORDERED_BY']),0,20,"...",'UTF-8') ?></td>
        <td class="no-border"><strong>Nama :</strong></td>
        <td class="no-border pull-right border-right-bold"> </td>
        <td class="no-border"><strong>Nama :</strong></td>
        <td class="no-border pull-right border-right" style="font-size:12;" colspan="4"><?= mb_strimwidth($items[0]['order']['approvedBy']['mpspProfile']['NAMA'],0,40,"...",'UTF-8') ?></td>
        <td class="no-border"><strong>Nama :</strong></td>
        <td class="no-border pull-right border-right"> </td>
    </tr>
    <tr>
        <td class="no-border"><strong>Jawatan :</strong></td>
        <td class="no-border pull-right border-right"> </td>
        <td class="no-border"><strong>Jawatan :</strong></td>
        <td class="no-border pull-right border-right-bold"> </td>
        <td class="no-border"><strong>Jawatan :</strong></td>
        <td class="no-border pull-right border-right" style="font-size:12;" colspan="4"><?= mb_strimwidth($items[0]['order']['approvedBy']['mpspProfile']['JAWATAN'],0,40,"...",'UTF-8') ?></td>
        <td class="no-border"><strong>Jawatan :</strong></td>
        <td class="no-border pull-right border-right"> </td>
    </tr>
    <tr>
        <td class="no-border"><strong>Jabatan :</strong></td>
        <td class="no-border pull-right border-right"> </td>
        <td class="no-border"><strong>Jabatan :</strong></td>
        <td class="no-border pull-right border-right-bold"> </td>
        <td class="no-border"><strong>Jabatan :</strong></td>
        <td class="no-border pull-right border-right" style="font-size:12;" colspan="4"><?= mb_strimwidth($items[0]['order']['approvedBy']['mpspProfile']['KETERANGAN'],0,40,"...",'UTF-8') ?></td>
        <td class="no-border"><strong>Jabatan :</strong></td>
        <td class="no-border pull-right border-right"> </td>
    </tr>
    <tr>
        <td class="no-border"><strong>Tarikh :</strong></td>
        <td class="no-border pull-right border-right" style="font-size:12;"><?= mb_strimwidth($items[0]['order']['ORDER_DATE'],0,40,"...",'UTF-8') ?></td>
        <td class="no-border"><strong>Tarikh :</strong></td>
        <td class="no-border pull-right border-right-bold"> </td>
        <td class="no-border"><strong>Tarikh :</strong></td>
        <td class="no-border pull-right border-right" style="font-size:12;" colspan="4"><?= mb_strimwidth($items[0]['order']['APPROVED_AT'],0,40,"...",'UTF-8') ?></td>
        <td class="no-border"><strong>Tarikh :</strong></td>
        <td class="no-border pull-right border-right"> </td>
    </tr>
    <tr>
        <td class="foot-note-col-1 foot-note-vertical-align-top border-right-bold" colspan="4" rowspan="3">
            <br><br>
            <p>Nota</p>
            <p>Salinan 1 - Disimpan oleh pemesan</p>
            <p>Salinan 2 - Bahagian Bekalan, Kawalan Dan Akaun</p>
            <p>Salinan 3 - Bahagian Simpanan</p>
            <p>Salinan 4 - Bahagian Bungkusan Dan Penghantaran</p>
            <p>Salinan 5 – Disimpan oleh  pemesan setelah stok diterima</p>
        </td>
        <td class="text-center foot-vertical-align-top text-center foot-deliver-head text-center info" colspan="7"><strong>BAHAGIAN BUNGKUSAN DAN,PENGHANTARAN</strong></td>
    </tr>
    <tr>
        <td class="vertical-align-top" colspan="2" rowspan="2"><strong>Butir-Butir Bungkusan</strong></td>
        <td class="vertical-align-top" colspan="3" rowspan="2"><strong>Butir-Butir Penghantaran</strong></td>
        <td class="vertical-align-top no-border" colspan="2">Telah dibungkus dan dihantar oleh :<br>..........................................................</td>
    </tr>
    <tr>
        <td class="vertical-align-top no-border" >
            <strong>Nama : </strong><br>
            <strong>Jawatan : </strong><br>
            <strong>Jabatan : </strong><br>
            <strong>Tarikh : </strong><br>
        </td>
        <td class="vertical-align-top no-border"> </td>
    </tr>

</tfoot>
</table>

</div>
</div>

frontend/views/official-form/_kewps11_2.php
            <tbody>
                <?php if (sizeof($items) >= 1) { ?>
                <?php foreach ($items as $i => $item) { ?>
                <tr>
                    <td class="text-center"><?= $i + 1 ?></td>
                    <td class="" colspan="2"><?= $item['inventory']['DESCRIPTION'] ?></td>
                    <td class="text-center" ><?= $item['RQ_QUANTITY'] ?></td>
                    <td class="text-center" ><?= $item['APP_QUANTITY'] ?></td>
                    <td class="text-center" ><?= $item['CURRENT_BALANCE'] ?></td>
                    <td class=""><?= $item['inventory']['CODE_NO'] ?></td>
                </tr>
                <?php } ?>
                <?php for ($j = sizeof($items); $j < 5; $j++) { ?>
                <tr>
                    <td class="text-center"> <?= $j + 1 ?></td>
                    <td class="text-center" colspan="2"> </td>
                    <td class="text-center" > </td>
                    <td class="text-center" > </td>
                    <td class="text-center" > </td>
                    <td class="text-center">&nbsp;</td>
                </tr>
                <?php } ?>
                <?php } else { ?>
                <?php for ($j = 0; $j < 5; $j++) { ?>
                <tr>
                    <td class="text-center"> <?= $j + 1 ?></td>
                    <td class="text-center" colspan="2"> </td>
                    <td class="text-center" > </td>
                    <td class="text-center" > </td>
                    <td class="text-center" > </td>
                    <td class="text-center">&nbsp;</td>
                </tr>
                <?php } ?>
                <?php } ?>
                <tbody>

frontend/views/official-form/_kewps11_3.php
            <tfoot>
                <tr>
                    <td class="no-border-bottom" colspan="4">
                    </td>
                    <td class="no-border-bottom" colspan="3"><strong>Kelulusan :</strong> <br>Permohonan diluluskan / tidak diluluskan*
                    </td>
                </tr>
                <tr>
                    <td class="no-border-bottom no-border-top" colspan="4">
                        <br><br>
                        <br><br>
                    </td>
                    <td class="no-border-bottom no-border-top" colspan="3">
                        <br><br>
                        <br><br>
                    </td>
                </tr>
                <tr>
                    <td class="no-border-top" colspan="4">
                        <p>............................................</p>
                        <p>(Tandatangan Pemohon)</p>
                    </td>
                    <td class="no-border-top" colspan="3">
                        <p>............................................</p>
                        <p>(Tandatangan Pegawai Pelulus)</p>
                    </td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">NAMA</td>
                    <td class="no-border-left" style="font-size:12;" colspan="2">: <?= mb_strimwidth($items[0]['order']['ORDERED_BY'],0,20,"...") ?></td>
                    <td class="no-border-right">NAMA</td>
                    <td class="no-border-left" style="font-size:12;" colspan="2">: <?= mb_strimwidth($items[0]['order']['approvedBy']['mpspProfile']['NAMA'],0,40,"...") ?></td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">JAWATAN</td>
                    <td class="no-border-left" colspan="2">:</td>
                    <td class="no-border-right">JAWATAN</td>
                    <td class="no-border-left" style="font-size:12;" colspan="2">: <?= mb_strimwidth($items[0]['order']['approvedBy']['mpspProfile']['JAWATAN'],0,40,"...") ?></td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">TARIKH</td>
                    <td class="no-border-left" colspan="2">: <?= $items[0]['order']['ORDER_DATE'] ?></td>
                    <td class="no-border-right">TARIKH</td>
                    <td class="no-border-left" colspan="2">: <?= $items[0]['order']['APPROVED_AT'] ?></td>
                </tr>
            </tfoot>
        </table>
        * sila potong yang berkenaan
        <br>
        <br>
        <table class="kv-grid-table table table-hover table-bordered ">
            <tbody>
                <tr>
                    <td class="no-border-bottom" colspan="6"><span><strong>Kemaskini Rekod :</strong></span></td>
                    <td class="no-border-bottom" colspan="6"><span><strong>Perakuan Penerimaan :</strong></span></td>
                </tr>
                <tr>
                    <td class="no-border-bottom wrap vertical-align-top" colspan="6"><span>Stok telah dikeluarkan dan direkod <br>di Kad Petak No  ... <?= $listItem ?> ...</span></td>
                    <td class="no-border-bottom wrap vertical-align-top" colspan="6"><span>Disahkan bahawa stok yang diluluskan telah diterima.</span></td>
                </tr>
                <tr>
                    <td class="no-border-bottom no-border-top" colspan="6"><br></td>
                    <td class="no-border-bottom no-border-top" colspan="6"><br></td>
                </tr>
                <tr>
                    <td class="no-border-top" colspan="6">
                        <p>............................................</p>
                        <p>(Tandatangan Pegawai Stor)</p>
                    </td>
                    <td class="no-border-top" colspan="6">
                        <p>............................................</p>
                        <p>(Tandatangan Pemohon / Wakil)</p>
                    </td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">NAMA</td>
                    <td class="no-border-left" style="font-size:12;" colspan="4">: <?= mb_strimwidth($items[0]['order']['creator']['mpspProfile']['NAMA'],0,40,"...") ?></td>
                    <td class="no-border-right" colspan="2">NAMA</td>
                    <td class="no-border-left" style="font-size:12;" colspan="4">: </td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">JAWATAN</td>
                    <td class="no-border-left" style="font-size:12;" colspan="4">: <?= mb_strimwidth($items[0]['order']['creator']['mpspProfile']['JAWATAN'],0,40,"...") ?></td>
                    <td class="no-border-right" colspan="2">JAWATAN</td>
                    <td class="no-border-left" colspan="4">:</td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">TARIKH</td>
                    <td class="no-border-left" colspan="4">: <?= $items[0]['order']['CREATED_AT'] ?></td>
                    <td class="no-border-right" colspan="2">TARIKH</td>
                    <td class="no-border-left" colspan="4">: </td>
                </tr>
            </tbody>>
        </table>

    </div>
</div>